### ISSUE TITLE
Math Captcha in Register form

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#36]
Support Forum issue
https://wordpress.org/support/topic/math-captcha-in-register-form-not-working/

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function um\core\Fields::field_error(), 1 passed in D:\OSPanel\domains\secondfs.local\wp-content\plugins\um-math-captcha\um-math-captcha.php on line 38 and at least 2 expected in D:\OSPanel\domains\secondfs.local\wp-content\plugins\ultimate-member\includes\core\class-fields.php:535
Stack trace:
#0 D:\OSPanel\domains\secondfs.local\wp-content\plugins\um-math-captcha\um-math-captcha.php(38): um\core\Fields->field_error()
#1 D:\OSPanel\domains\secondfs.local\wp-includes\class-wp-hook.php(310): um_math_captcha_field()
#2 D:\OSPanel\domains\secondfs.local\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters()
#3 D:\OSPanel\domains\secondfs.local\wp-includes\plugin.php(517): WP_Hook->do_action()
#4 D:\OSPanel\domains\secondfs.local\wp-content\plugins\ultimate-member\templates\register.php(37): do_action()
#5 D:\OSPanel\domains\secondfs.local\wp-content\plugins\ultimate-member\includes\core\class-shortcodes.php(332): include('D:\\OSPanel\\doma...')
#6 D:\OSPane in D:\OSPanel\domains\secondfs.local\wp-content\plugins\ultimate-member\includes\core\class-fields.php on line 535
```

**Comment by champsupertramp** [comment]
Hi @MissVeronica   Thanks for the report. This has been fixed in this pre-release version: https://github.com/ultimatemember/Extended/releases/tag/2.0.0-alpha2
