### ISSUE TITLE
Ultimate Member - Math Captcha in Register form

### ISSUE THREAD

**Issue by yuriinalivaiko** [ultimatemember/Extended#37]
The **Ultimate Member - Math Captcha in Register form** plugin causes an error.

```
[22-Oct-2023 20:03:23 UTC] PHP Warning:  Trying to access array offset on value of type null in D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-fields.php on line 627
[22-Oct-2023 20:03:23 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function um\core\Fields::field_error(), 1 passed in D:\web\um\wp-content\plugins\um-math-captcha\um-math-captcha.php on line 38 and at least 2 expected in D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-fields.php:535
Stack trace:
#0 D:\web\um\wp-content\plugins\um-math-captcha\um-math-captcha.php(38): um\core\Fields->field_error(NULL)
#1 D:\web\um\wp-includes\class-wp-hook.php(324): um_math_captcha_field(Array)
#2 D:\web\um\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 D:\web\um\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#4 D:\web\um\wp-content\plugins\ultimate-member\templates\register.php(37): do_action('um_after_regist...', Array)
#5 D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-shortcodes.php(332): include('D:\\web\\um\\wp-co...')
#6 D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-shortcodes.php(993): um\core\Shortcodes->load_template('register')
#7 D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-shortcodes.php(895): um\core\Shortcodes->template_load('register', Array)
#8 D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-shortcodes.php(647): um\core\Shortcodes->load(Array)
#9 D:\web\um\wp-includes\shortcodes.php(433): um\core\Shortcodes->ultimatemember(Array, '', 'ultimatemember')
#10 [internal function]: do_shortcode_tag(Array)
#11 D:\web\um\wp-includes\shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(ultima...', 'do_shortcode_ta...', '[ultimatemember...')
#12 D:\web\um\wp-includes\class-wp-hook.php(324): do_shortcode('[ultimatemember...')
#13 D:\web\um\wp-includes\plugin.php(205): WP_Hook->apply_filters('[ultimatemember...', Array)
#14 D:\web\um\wp-includes\post-template.php(256): apply_filters('the_content', '<!-- wp:shortco...')
#15 D:\web\um\wp-content\themes\twentytwentyone\template-parts\content\content-page.php(29): the_content()
#16 D:\web\um\wp-includes\template.php(792): require('D:\\web\\um\\wp-co...')
#17 D:\web\um\wp-includes\template.php(725): load_template('D:\\web\\um/wp-co...', false, Array)
#18 D:\web\um\wp-includes\general-template.php(206): locate_template(Array, true, false, Array)
#19 D:\web\um\wp-content\themes\twentytwentyone\page.php(17): get_template_part('template-parts/...')
#20 D:\web\um\wp-includes\template-loader.php(106): include('D:\\web\\um\\wp-co...')
#21 D:\web\um\wp-blog-header.php(19): require_once('D:\\web\\um\\wp-in...')
#22 D:\web\um\index.php(17): require('D:\\web\\um\\wp-bl...')
#23 {main}
  thrown in D:\web\um\wp-content\plugins\ultimate-member\includes\core\class-fields.php on line 535
```

**Comment by champsupertramp** [comment]
Hi @yuriinalivaiko  Thanks for the report. This has been fixed in this pre-release version: https://github.com/ultimatemember/Extended/releases/tag/2.0.0-alpha2
