### ISSUE TITLE
UM Extended - 2.1.0-beta.15

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#86]
Impossible to activate the uploaded ZIP file with UM Extended - 2.1.0-beta.15

Invalid Class Name: UM_Extended_Country_Flag\Core

**Comment by champsupertramp** [comment]
Hi @MissVeronica  - I couldn't reproduce this issue with 2.1.0-beta.15. 

Did you download it from the Releases page? https://github.com/ultimatemember/Extended/releases/tag/2.1.0-beta.15

**Comment by MissVeronica** [comment]
Yes download from your link and I got same error today after a new download.
There is nothing by WP written to debug.log
Same error with both PHP 7.4.33 and 8.3.6

A backtrace by my coding when WP is doing the redirect:

`.../wp-admin/plugins.php?error=true&plugin=Extended-2.1.0-beta.15%2Fum-extended.php&_error_nonce=caacbb5e73`
 
from:
```
plugin.php:205
pluggable.php:1433
includes/plugin.php:669
plugins.php:60
```

**Comment by MissVeronica** [comment]
Now I have made a deactivation of all plugins except UM and activated the Twenty Twenty theme.
Still the same `Invalid Class Name: UM_Extended_Country_Flag\Core`

**Comment by MissVeronica** [comment]
**Finally got "2.1.0-beta.15" activating OK**

My log shows the same error strings as before but it's ignored by WP in the WP redirect because the plugin is activated from "Recently Actived" plugins???

`.../wp-admin/plugins.php?activate=true&plugin_status=recently_activated&paged=1&s=`

For me this is a WP issue now.

Comments??

**Comment by MissVeronica** [comment]
I added a stackdump trace at  `/wp-includes/functions.php` at line 6078
and it's pointing at `um-extended.php(186): wp_die()`
```
			if ( class_exists( $class_name ) ) {
				$this->funcs[ $func_name ] = function () use ( $class_name, $slug ) {

					if ( ! isset( $this->classes[ $slug ] ) ) {
						$this->classes[ $slug ] = new $class_name( __FILE__ );
					}
					return $this->classes[ $slug ];
				};

				call_user_func( array( $this, $func_name ) );
			} elseif ( ! defined( 'WP_CLI' ) ) {
					wp_die( esc_attr( 'Invalid Class Name: ' . $class_name ) );
			}
```
```
#0 wp-includes/functions.php(6022): wp_trigger_error()
#1 wp-includes/query.php(882): _doing_it_wrong()
#2 wp-includes/robots-template.php(93): is_embed()
#3 wp-includes/class-wp-hook.php(324): wp_robots_noindex_embeds()
#4 wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 wp-includes/robots-template.php(32): apply_filters()
#6 wp-includes/functions.php(3863): wp_robots()
#7 wp-includes/functions.php(3785): _default_wp_die_handler()
#8 wp-content/plugins/Extended-2.1.0-beta.15/um-extended.php(186): wp_die()
#9 wp-content/plugins/Extended-2.1.0-beta.15/um-extended.php(122): UM_Extended->um_extended_construct()
#10 wp-content/plugins/Extended-2.1.0-beta.15/um-extended.php(211): UM_Extended::instance()
#11 wp-content/plugins/Extended-2.1.0-beta.15/um-extended.php(213): um_extended_plugin()
#12 wp-settings.php(517): include_once('/home/...')
#13 wp-config.php(88): require_once('/home/...')
#14 wp-load.php(50): require_once('/home/...')
#15 wp-admin/admin.php(34): require_once('/home/...')
#16 wp-admin/plugins.php(10): require_once('/home/...')
#17 {main}
```

**Comment by MissVeronica** [comment]
Trace from the foreach loop in `um-extended.php`

count extensions: 6
foreach: i=0 ext=um-country-flag
name: Country_Flag
slug: country-flag
class_name: UM_Extended_Country_Flag\Core

**Comment by champsupertramp** [comment]
Hi @MissVeronica  - I couldn't reproduce this issue with the beta, maybe this PR would fix the issue on your end?
https://github.com/ultimatemember/Extended/pull/89

Here's with the compiled version:
https://ultimatemember.wpdocker.io/downloads/token/69454965-0132-4404-b179-eb83c89a05bd

**Comment by MissVeronica** [comment]
No, the same error now with `Invalid Class Name: \UM_Extended_Country_Flag\Core`
I made the changes in `um-extended.php`

**Comment by MissVeronica** [comment]
How can the `\UM_Extended_Country_Flag\Core` class be active during activation of "2.1.0-beta.15" ????

"2.1.0-beta.15" is reading the option `um_extended_active_extensions` which was written by "Version 2.0.5" and contains 6 entries.

I have tried with "Version 2.0.5" active before activating "2.1.0-beta.15" and I get "PHP Fatal error:  Cannot redeclare um_extended_plugin()".

I deactivated all 6 extended plugins with "Version 2.0.5" 
Deactivated "Version 2.0.5"
Activated "2.1.0-beta.15" now OK when there are extended plugins activated
Activated all 6 extended plugins with "2.1.0-beta.15"

It's the only solution with current version of "2.1.0-beta.15"

### Impossible to activate the uploaded ZIP file with UM Extended - 2.1.0-beta.15 if you have extended plugins activated by an older version of UM Extended
